# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/ethereum-node.yaml.j2

teku-geth-001:
  global:
    main:
      network: pectra-devnet-0
      engineEndpoint: http://geth-teku-001:8551
      rpcEndpoint: http://geth-teku-001:8545
      beaconEndpoint: http://teku-geth-001:5052
    checkpointSync:
      enabled: false
      addresses:
        pectra-devnet-0: https://<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.dencun-devnets.node_ingress.combined}>@bn.bootnode-1.srv.pectra-devnet-0.ethpandaops.io
    clientArgs:
      networks:
        pectra-devnet-0:
          execution:
            besu:
              - --genesis-file=/data/network-config/besu.json
              - --bootnodes=enode://91828090906020d9319c3bc409b24dc6152e4064916749f71180db7884a0d9f2fddd47e19052283fd1916c329f9f35e287a09a118865eaad5b54cc4b33d9deba@104.248.129.151:30303?discport=30303
              - --rpc-http-api=ADMIN,DEBUG,ETH,MINER,NET,TRACE,TXPOOL,WEB3
              - --sync-mode=FULL
              - --data-storage-format=BONSAI
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.ethstats_secret}>@ethstats.pectra-devnet-0.ethpandaops.io:443
            nethermind:
              - --Init.ChainSpecPath=/data/network-config/chainspec.json
              - --JsonRpc.EnabledModules=Eth,Subscribe,Trace,TxPool,Web3,Personal,Proof,Net,Parity,Health,Rpc,Debug,Admin
              - --Discovery.Bootnodes=enode://91828090906020d9319c3bc409b24dc6152e4064916749f71180db7884a0d9f2fddd47e19052283fd1916c329f9f35e287a09a118865eaad5b54cc4b33d9deba@104.248.129.151:30303?discport=30303
              - --Init.IsMining=false
              - --Pruning.Mode=None
              - --config=none.cfg
              - --EthStats.Enabled=true
              - --EthStats.Name=k8s-teku-geth-001
              - --EthStats.Secret=<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.ethstats_secret}>
              - --EthStats.Server=wss://ethstats.pectra-devnet-0.ethpandaops.io/api/
              - --log=INFO
            geth:
              - --http.api=eth,net,web3,debug,admin
              - --http.vhosts=*
              - --state.scheme=path
              - --networkid=7011893080
              - --syncmode=full
              - --bootnodes=enode://91828090906020d9319c3bc409b24dc6152e4064916749f71180db7884a0d9f2fddd47e19052283fd1916c329f9f35e287a09a118865eaad5b54cc4b33d9deba@104.248.129.151:30303?discport=30303
              - --ethstats=k8s-teku-geth-001:<path:/secrets/services/services.enc.yaml#ethereum | jsonPath {.testnets.pectra-devnets.ethstats_secret}>@ethstats.pectra-devnet-0.ethpandaops.io
              - --rpc.allow-unprotected-txs
            erigon:
            ethereumjs:
              - --gethGenesis=/data/network-config/genesis.json
              - --bootnodes=enode://91828090906020d9319c3bc409b24dc6152e4064916749f71180db7884a0d9f2fddd47e19052283fd1916c329f9f35e287a09a118865eaad5b54cc4b33d9deba@104.248.129.151:30303?discport=30303
              - --maxPeers=75
              - --isSingleNode=true
          consensus:
            lodestar:
              - --paramsFile=/data/network-config/config.yaml
              - --genesisStateFile=/data/network-config/genesis.ssz
              - --bootnodes=enr:-Iq4QKK8s4gMKy_OpDxvO6EMrmjPxp_-jeGQu2mgCgSpC7YmZNIlW3OxkThf1zzCRAeFnFr-Iionm8jZQX5F6UzQatOGAY981BhhgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-LK4QKOlHAef5n0UzsGH7sZRIaEYs59y_givEbMtz_Qs5L12YI8x-EJKMkUJbAHk07d-zSsBGSpH1c5KD55xpuT65NoEh2F0dG5ldHOIAAAAAAAADACEZXRoMpAAOoTkYFKIEQIAAAAAAAAAgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQOP66O5XQ6sHdfMLl6ALWwHot6Upbxc7wTDisGWw8OTlYN0Y3CCIyiDdWRwgiMo
              - --rest.namespace="*"
              - --network.connectToDiscv5Bootnodes
              - --nat=true
              - --chain.persistInvalidSszObjects=true
            teku:
              - --network=/network-config/config.yaml
              - --genesis-state=/network-config/genesis.ssz
              - --p2p-discovery-bootnodes=enr:-Iq4QKK8s4gMKy_OpDxvO6EMrmjPxp_-jeGQu2mgCgSpC7YmZNIlW3OxkThf1zzCRAeFnFr-Iionm8jZQX5F6UzQatOGAY981BhhgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-LK4QKOlHAef5n0UzsGH7sZRIaEYs59y_givEbMtz_Qs5L12YI8x-EJKMkUJbAHk07d-zSsBGSpH1c5KD55xpuT65NoEh2F0dG5ldHOIAAAAAAAADACEZXRoMpAAOoTkYFKIEQIAAAAAAAAAgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQOP66O5XQ6sHdfMLl6ALWwHot6Upbxc7wTDisGWw8OTlYN0Y3CCIyiDdWRwgiMo
              - --data-storage-mode=ARCHIVE
              - --Xepochs-store-blobs=max # Keep the blobs forever
              - --ignore-weak-subjectivity-period-enabled
            prysm:
              - --grpc-gateway-corsdomain=*
              - --chain-config-file=/data/network-config/config.yaml
              - --genesis-state=/data/network-config/genesis.ssz
              - --contract-deployment-block=0
              - --min-sync-peers=1
              - --pprof
              - --enable-debug-rpc-endpoints
              - --verbosity=debug
              - --subscribe-all-subnets
              - --bootstrap-node=enr:-Iq4QKK8s4gMKy_OpDxvO6EMrmjPxp_-jeGQu2mgCgSpC7YmZNIlW3OxkThf1zzCRAeFnFr-Iionm8jZQX5F6UzQatOGAY981BhhgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk
              - --bootstrap-node=enr:-LK4QKOlHAef5n0UzsGH7sZRIaEYs59y_givEbMtz_Qs5L12YI8x-EJKMkUJbAHk07d-zSsBGSpH1c5KD55xpuT65NoEh2F0dG5ldHOIAAAAAAAADACEZXRoMpAAOoTkYFKIEQIAAAAAAAAAgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQOP66O5XQ6sHdfMLl6ALWwHot6Upbxc7wTDisGWw8OTlYN0Y3CCIyiDdWRwgiMo
            lighthouse:
              - --testnet-dir=/data/network-config
              - --boot-nodes=enr:-Iq4QKK8s4gMKy_OpDxvO6EMrmjPxp_-jeGQu2mgCgSpC7YmZNIlW3OxkThf1zzCRAeFnFr-Iionm8jZQX5F6UzQatOGAY981BhhgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk,enr:-LK4QKOlHAef5n0UzsGH7sZRIaEYs59y_givEbMtz_Qs5L12YI8x-EJKMkUJbAHk07d-zSsBGSpH1c5KD55xpuT65NoEh2F0dG5ldHOIAAAAAAAADACEZXRoMpAAOoTkYFKIEQIAAAAAAAAAgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQOP66O5XQ6sHdfMLl6ALWwHot6Upbxc7wTDisGWw8OTlYN0Y3CCIyiDdWRwgiMo
              - --allow-insecure-genesis-sync
            nimbus:
              - --network=/data/network-config
              - --validator-monitor-auto=false
              - --doppelganger-detection=off
              - --log-level=DEBUG;INFO:gossip_eth2,attpool,libp2p,gossipsub,pubsubpeer,pubsub,switch,networking,sync,dialer,identify,syncman,connmanager,beacnde,lightcl,requman,gossip_lc,clearance,lpstream,mplexchannel,nodes-verification,tcptransport,chaindag,noise,eth,p2p,discv5,muxedupgrade,multistream,connection,secure,fee_recipient,mplex,syncpool,multiaddress,peer_proto;WARN:message_router
              - --light-client-data-serve=false
              - --graffiti=parithoshs-MacBook-Pro
              - --bootstrap-node=enr:-Iq4QKK8s4gMKy_OpDxvO6EMrmjPxp_-jeGQu2mgCgSpC7YmZNIlW3OxkThf1zzCRAeFnFr-Iionm8jZQX5F6UzQatOGAY981BhhgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQJJ3h8aUO3GJHv-bdvHtsQZ2OEisutelYfGjXO4lSg8BYN1ZHCCIyk
              - --bootstrap-node=enr:-LK4QKOlHAef5n0UzsGH7sZRIaEYs59y_givEbMtz_Qs5L12YI8x-EJKMkUJbAHk07d-zSsBGSpH1c5KD55xpuT65NoEh2F0dG5ldHOIAAAAAAAADACEZXRoMpAAOoTkYFKIEQIAAAAAAAAAgmlkgnY0gmlwhGj4gZeJc2VjcDI1NmsxoQOP66O5XQ6sHdfMLl6ALWwHot6Upbxc7wTDisGWw8OTlYN0Y3CCIyiDdWRwgiMo


  geth:
    enabled: true
    fullnameOverride: geth-teku-001
    image:
      repository: ethpandaops/geth
      tag: bad-block-nil-check
      pullPolicy: Always
    p2pNodePort:
      enabled: false
    persistence:
      enabled: true
      size: 100Gi
    podLabels:
      network: pectra-devnet-0
      testnet: pectra-devnet-0
      ethereum_network: pectra-devnet-0
      ethereum_role: execution
      consensus_client: teku
      execution_client: geth
      ethereum_instance: geth-teku-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            CHAINSPEC_URI=https://config.pectra-devnet-0.ethpandaops.io/el/chainspec.json;
            GENESIS_URI=https://config.pectra-devnet-0.ethpandaops.io/el/genesis.json;
            BESU_GENESIS_URI=https://config.pectra-devnet-0.ethpandaops.io/el/besu.json;
            BOOTNODES_URI=https://config.pectra-devnet-0.ethpandaops.io/el/bootnodes.txt;
            mkdir -p /data/network-config;
            if ! [ -f /data/network_config_init_done ];
            then
              apk update && apk add curl jq;
              wget -O /data/network-config/chainspec.json $CHAINSPEC_URI;
              wget -O /data/network-config/genesis.json $GENESIS_URI;
              wget -O /data/network-config/besu.json $BESU_GENESIS_URI;
              wget -O /data/network-config/bootnodes.txt $BOOTNODES_URI;
              cat /data/network-config/genesis.json | jq -r '.config.chainId' > /data/network-config/chainid.txt;
              touch /data/network_config_init_done;
              echo "network config init done";
            else
              echo "network config already present";
            fi;
            echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
        volumeMounts:
          - name: storage
            mountPath: "/data"
      - name: init-genesis
        image: ethpandaops/geth:bad-block-nil-check
        imagePullPolicy: Always
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
          - sh
          - -ace
          - >
            if ! [ -f /data/genesis_init_done ];
            then
              geth init --state.scheme=path --datadir /data /data/network-config/genesis.json;
              touch /data/genesis_init_done;
              echo "genesis init done";
            else
              echo "genesis is already initialized";
            fi;
        volumeMounts:
          - name: storage
            mountPath: "/data"

  teku:
    enabled: true
    fullnameOverride: teku-geth-001
    image:
      repository: ethpandaops/teku
      tag: master-8f4e64a
      pullPolicy: Always
    mode: "beacon"
    p2pNodePort:
      enabled: false
    podLabels:
      network: pectra-devnet-0
      testnet: pectra-devnet-0
      ethereum_network: pectra-devnet-0
      ethereum_role: consensus
      consensus_client: teku
      execution_client: geth
      ethereum_instance: teku-geth-001
    resources:
      requests:
        cpu: 2000m
        memory: 5Gi
      limits:
        cpu: 3000m
        memory: 7Gi
    persistence:
      enabled: true
      size: 200Gi
    initContainers:
    - name: init-genesis
      image: alpine:latest
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
      command:
        - sh
        - -ace
        - >
          apk add jq curl sed;
          DEPOSIT_CONTRACT_URI=https://config.pectra-devnet-0.ethpandaops.io/deposit_contract.txt;
          DEPOSIT_CONTRACT_BLOCK_URI=https://config.pectra-devnet-0.ethpandaops.io/cl/deposit_contract_block.txt;
          DEPLOY_BLOCK_URI=https://config.pectra-devnet-0.ethpandaops.io/cl/deploy_block.txt;
          GENESIS_CONFIG_URI=https://config.pectra-devnet-0.ethpandaops.io/cl/config.yaml;
          GENESIS_SSZ_URI=https://config.pectra-devnet-0.ethpandaops.io/cl/genesis.ssz;
          mkdir -p /data/network-config;
          curl -s https://config.pectra-devnet-0.ethpandaops.io/api/v1/nodes/inventory | jq -r '.ethereum_pairs[] | .consensus.enr' > /data/network-config/bootnodes.txt;
          if ! [ -f /data/network-config/genesis.ssz ];
          then
            wget -O /data/network-config/deposit_contract.txt $DEPOSIT_CONTRACT_URI;
            wget -O /data/network-config/deposit_contract_block.txt $DEPOSIT_CONTRACT_BLOCK_URI;
            wget -O /data/network-config/deploy_block.txt $DEPLOY_BLOCK_URI;
            wget -O /data/network-config/config.yaml $GENESIS_CONFIG_URI;
            wget -O /data/network-config/genesis.ssz $GENESIS_SSZ_URI;
            echo "genesis init done";
          else
            echo "genesis exists. skipping...";
          fi;
          (tr '\n' ',' < /data/network-config/bootnodes.txt | sed 's/[^,]*/"&"/g') > /data/network-config/bootnodes2.txt;
          mv /data/network-config/bootnodes2.txt /data/network-config/bootnodes.txt;
          echo "bootnode init done: $(cat /data/network-config/bootnodes.txt)";
      volumeMounts:
        - name: storage
          mountPath: "/data"
