# Ansible managed. Don't change this file manually. Template info: /vendor/collections/ansible_collections/ethpandaops/general/roles/generate_kubernetes_config/templates/blockscout.yaml.j2

blockscout-stack:
  fullnameOverride: blockscout
  config:
    network:
      id: 7042905162
      name: pectra-devnet-4
      shortname: pectra-devnet-4
      currency:
        name: Ether
        symbol: ETH
        decimals: 18
        dualToken: false
    account:
      enabled: false
    testnet: true
    nameService:
      enabled: true
      url: "https://explorer.pectra-devnet-4.ethpandaops.io"
    prometheus:
      enabled: false
  postgresql:
    enabled: true
    fullnameOverride: blockscout-postgresql
    primary:
      persistence:
        size: "100Gi"

## Configuration options for backend
  blockscout:
    podAnnotations:
      "promtail.io/ignore_pod": "true"
    image:
      repository: blockscout/blockscout
      tag: 6.8.1
      pullPolicy: IfNotPresent
    env:
      ETHEREUM_JSONRPC_VARIANT: "geth"
      ETHEREUM_JSONRPC_HTTP_URL: http://geth-teku-001:8545
      ETHEREUM_JSONRPC_WS_URL: ws://geth-teku-001:8546
      ETHEREUM_JSONRPC_TRACE_URL: http://geth-teku-001:8545
      COIN: ETH
      DATABASE_URL: postgres://postgres:postgres@blockscout-postgresql:5432/blockscout?ssl=false
      DISABLE_EXCHANGE_RATES: "true"
      ECTO_USE_SSL: "false"


      INDEXER_COIN_BALANCES_BATCH_SIZE: "5"
      NETWORK: Ethereum
      SUBNETWORK: pectra-devnet-4

      POOL_SIZE: "15"
      CHAIN_SPEC_PATH: /config-update/chainspec.json
    extraVolumes:
      - name: config-update
        emptyDir: {}

    extraVolumeMounts:
      - name: config-update
        mountPath: "/config-update"

    initContainers:
      - name: init-config
        image: alpine:latest
        imagePullPolicy: IfNotPresent
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command:
        - sh
        - -ace
        - >
          CHAINSPEC=https://config.pectra-devnet-4.ethpandaops.io/el/chainspec.json;
          mkdir -p /config-update;
          wget -O /config-update/chainspec.json $CHAINSPEC;
          echo "got genesis";
          /bin/blockscout eval "Elixir.Explorer.ReleaseTasks.create_and_migrate()"
        volumeMounts:
          - name: config-update
            mountPath: /config-update




  frontend:
    image:
      repository: ghcr.io/blockscout/frontend
      tag: latest
      pullPolicy: Always
    podAnnotations:
      "promtail.io/ignore_pod": "true"
    ingress:
      enabled: true
      className: ingress-nginx-public
      hosts:
        - host: explorer.pectra-devnet-4.ethpandaops.io
          paths:
            - path: /
              pathType: Prefix
    env:
      NEXT_PUBLIC_NETWORK_NAME: pectra-devnet-4
      NEXT_PUBLIC_NETWORK_ID: 7042905162
      NEXT_PUBLIC_NETWORK_RPC_URL: https://rpc.pectra-devnet-4.pectra-devnet-4.ethpandaops.io
      NEXT_PUBLIC_APP_PROTOCOL: https